# JJP added a comment line to enable Commit changes...
name: Stage the app
on:
  pull_request:
    types: [labeled]
jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'stage')
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
